apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  namespace: default
spec:
  selector:
    app: gitops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8095
      nodePort: 30080
  type: NodePort

